services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:8080"

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: authentication-service.Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DSN=postgresql://neondb_owner:npg_cVwRfym2n8lb@ep-blue-base-adcmddes-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: logger-service.Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=mongodb+srv://everest:kaiseho12@cluster0.hodtqt5.mongodb.net/?appName=Cluster0
    
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
