services:
  broker-service:
    build:
      context: ./../broker-service
      dockerfile: broker-service.Dockerfile
    restart: always
    ports:
      - "8080:8080"

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: authentication-service.Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DSN=postgresql://neondb_owner:npg_cVwRfym2n8lb@ep-blue-base-adcmddes-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require

  logger-service:
    build:
      context: ./../logger-service
      dockerfile: logger-service.Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=mongodb+srv://everest:kaiseho12@cluster0.hodtqt5.mongodb.net/?appName=Cluster0

  mailer-service:
    build:
      context: ./../mailer-service
      dockerfile: mailer-service.Dockerfile
    restart: always
    ports:
      - "8083:8083"
    environment:
      - MAIL_DOMAIN=localhost
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MAIL_USERNAME=""
      - MAIL_PASSWORD=""
      - MAIL_ENCRYPTION=none
      - FROM_NAME="My App Support"
      - FROM_ADDRESS="support@example.com"

  listener-service: # Fixed spelling and quote
    build:
      context: ./../listener-service # Fixed spacing and spelling
      dockerfile: listener-service.Dockerfile
    deploy: 
      mode: replicated
      replicas: 1 # Added space after colon
  
  mailhog:
    image: 'mailhog/mailhog:latest'
    restart: always
    ports:
      - "1025:1025" 
      - "8025:8025"
    
  rabbitmq:
    image: 'rabbitmq:3.9-management-alpine' # Suggestion: use management tag for UI
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI port
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/